basePath: /
definitions:
  fiber.Map:
    additionalProperties: true
    type: object
  models.RiderRequest:
    properties:
      coordinates:
        items:
          type: number
        type: array
      id:
        type: string
      radius:
        type: number
      type:
        type: string
    required:
    - coordinates
    - radius
    - type
    type: object
  responses.RiderResponse:
    properties:
      data:
        $ref: '#/definitions/fiber.Map'
      message:
        type: string
      status:
        type: integer
    type: object
host: localhost:8000
info:
  contact:
    email: meozler@gmail.com
    name: Mert Özler
    url: http://github.com/mertozler
  description: Find the nearest driver to rider.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Matching API
  version: "1.0"
paths:
  /findDriver:
    post:
      consumes:
      - application/json
      description: The endpoint that allows searching with a GeoJSON point to find
        a driver if it matches the given criteria. Otherwise, the service should respond
        with a 404 - Not Found
      parameters:
      - description: 'Authentication header: (You need to add Bearer to the beginning
          of the jwt key. For example: Bearer apiKey)'
        in: header
        name: Authorization
        required: true
        type: string
      - description: Rider data
        in: body
        name: rider
        required: true
        schema:
          $ref: '#/definitions/models.RiderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.RiderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.RiderResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responses.RiderResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.RiderResponse'
      summary: Find The Driver
      tags:
      - Matching
swagger: "2.0"
